### ISSUE TITLE
Completely full BitBuffers add an extra byte when converted to byte arrays

### ISSUE THREAD

**Issue by granthenke** [magik6k/BitBuffer#9]
The example code below prints out a length of 2 when its expected to be 1:

```java
BitBuffer buffer = BitBuffer.allocate(8);
buffer.putByte((byte) 128, 8);
System.out.println(buffer.asByteArray().length);
```

**Comment by magik6k** [comment]
Should soon be downloadable from maven central as 1.5.1. Thanks for the report!

**Comment by granthenke** [comment]
@magik6k Awesome, thanks for the quick fix. Didn't even realize you published to maven. You should add some of that information to the README.
